### ISSUE TITLE
Stepper Reset

### ISSUE THREAD

**Issue by brandiweekes** [brandiweekes/HawkBox#6]
https://github.com/brandiweekes/HawkBox/blob/583ed6dc89925a6975fb8e8e3175ad47c38ec84a/Crawl/Crawl/Views/Characters/CharacterEditPage.xaml.cs#L76

As is, it resets the stepper; without Sam's implementation, if you take following steps:

1. edit
2. change a stepper
3. cancel
4. edit same character
   --> stepper was not reset; retains step 2 change

Sam's implementation works, but is there another way?

further investigate this implementation, re: professor's comments

> Seems odd to reset the Data object values on cancel.

**Comment by sandells** [comment]
Found another way to do the steppers:
-changed the binding mode on the steppers to OneTime
-changed the labels for the steppers to bind to the stepper value instead of the attribute value
-update the attribute values by setting them based on the label values in the save event handler

With this method it is not necessary to reset the values on cancel, and we don't need event handlers for each individual stepper.

**Comment by brandiweekes** [comment]
fixed
